routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*---routes avec arguments ou noms----*/
Route::get('hello', function () {
    return 'welcome people';
});

// Route::get('hello/{name}', function ($name) {
//     return "welcome $name";
// });

Route::get('hello/{name}-{id}', function ($name,$id) {
    return "welcome $name votre ID: $id";
})-> where('name', '[a-z0-9\-]+')-> where('id', '[0-9]+');


/*--- route accueil---*/
Route::get('/', function () {
    return view('welcome');
});

Route::resource('bakelarav', 'BakelaravController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Bakelarav.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bakelarav extends Model
{
    //
    protected $fillable = [
        'bakeliste',
        'email',
        'description',      
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BakelaravController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Bakelarav;

class BakelaravController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $bakelaravs = Bakelarav::all();

        return view('bakelistes.index', compact('bakelaravs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('bakelistes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'bakeliste'=>'required',
            'email'=>'required',
            'description'=>'required',
        ]);

        if ($this == TRUE){
            $req = $request;
        }

        $bakelaravUser = new Bakelarav([
            'bakeliste' => $req->get('bakeliste'),
            'email' => $req->get('email'),
            'description' => $req->get('description'),
        ]);
        $bakelaravUser->save();
        return redirect('/bakelarav')->with('success', 'Bakeliste Enregistre!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $bakelarav = Bakelarav::find($id);
        return view('bakelistes.edit', compact('bakelarav'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
            'bakeliste'=>'required',
            'description'=>'required',
            'email'=>'required',
        ]);

        if ($this == TRUE){
            $req = $request;
        }

        $bakelarav = Bakelarav::find($id);
        $bakelarav->bakeliste =  $req->get('bakeliste');
        $bakelarav->email = $req->get('email');
        $bakelarav->description = $req->get('description');
        $bakelarav->save();

        return redirect('/bakelarav')->with('success', 'Bakeliste Modifié!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $bakelarav = Bakelarav::find($id);
        $bakelarav->delete();

        return redirect('/bakelarav')->with('success', 'Bakeliste Supprimé!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/bakelistes/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Ajouter un Bakeliste</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('bakelarav.store') }}">
          {!! csrf_field() !!}
          <div class="form-group">    
              <label for="bakeliste">Nom du bakeliste:</label>
              <input type="text" class="form-control" name="bakeliste"/>
          </div>
       
          <div class="form-group">
              <label for="email">Email:</label>
              <input type="text" class="form-control" name="email"/>
          </div>
          <div class="form-group">
              <label for="description">Description:</label>
              <input type="text" class="form-control" name="description"/>
          </div>
          
                                 
          <button type="submit" class="btn btn-primary-outline">Ajouter Bakeliste</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/bakelistes/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Modification Bakeliste</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('bakelarav.update', $bakelarav->id) }}">
            <!-- @method('PATCH') 
            @csrf -->
            {{!! method_field('PATCH') !!}} 
            {{!! csrf_field() !!}}
            <div class="form-group">

                <label for="bakeliste">Nom Bakeliste:</label>
                <input type="text" class="form-control" name="bakeliste" value={{ $bakelarav->bakeliste }} />
            </div>
            
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="text" class="form-control" name="email" value={{ $bakelarav->email }} />
            </div>
            <div class="form-group">
                <label for="description">Description:</label>
                <input type="text" class="form-control" name="description" value={{ $bakelarav->description }} />
            </div>
            <button type="submit" class="btn btn-primary">Modifier</button>
        </form>
    </div>
</div>
@endsection

resources/views/bakelistes/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Bakelistes</h1>    
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nom</td>
          <td>Email</td>
          <td>Description</td>
          <td colspan = 2>Actions</td>
        </tr>
        <div>
          <a style="margin: 19px;" href="{{ route('bakelarav.create')}}" class="btn btn-primary">New Bakeliste</a>
        </div>
    </thead>

    
    <tbody>
        @foreach($bakelaravs as $bakelarav)
        <tr>
            <td>{{$bakelarav->id}}</td>
            <td>{{$bakelarav->bakeliste}}</td>
            <td>{{$bakelarav->email}}</td>
            <td>{{$bakelarav->description}}</td>
            <td>
                <a href="{{ route('bakelarav.edit',$bakelarav->id)}}" class="btn btn-primary">Modifier</a>
            </td>
            <td>
                <form action="{{ route('bakelarav.destroy', $bakelarav->id)}}" method="post">
                <!-- les cotes sont valables pour la version laravel 5.1 pour les versions
                 superieurs a 5.6 ont mets le @csrf et @method('delete') -->
                {!! csrf_field() !!}
                {!! method_field('DELETE') !!}
                  <button class="btn btn-danger" type="submit">Supprimer</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
</div>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
@endsection

resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Laravel 5 & MySQL CRUD </title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
  <div class="container">
    @yield('main')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>